spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/isa
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRINT_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver

    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.xml